/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login_registro;

import bancoDados.dados;
import java.awt.Color;

/**
 *
 * @author FakeKing
 */
public class telaLogin extends javax.swing.JFrame {

    /**
     * Creates new form telaLogin
     */
    public telaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        tittle = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        inputPass = new javax.swing.JPasswordField();
        buttonLogar = new javax.swing.JButton();
        direitos = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        inputUser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_registro/logo.png"))); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("login_registro/Bundle"); // NOI18N
        logo.setText(bundle.getString("telaLogin.logo.text")); // NOI18N
        getContentPane().add(logo);
        logo.setBounds(-60, 20, 390, 300);

        tittle.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        tittle.setForeground(new java.awt.Color(255, 255, 255));
        tittle.setText(bundle.getString("telaLogin.tittle.text")); // NOI18N
        getContentPane().add(tittle);
        tittle.setBounds(400, 30, 330, 42);

        status.setForeground(new java.awt.Color(255, 255, 255));
        status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        status.setText(bundle.getString("telaLogin.status.text")); // NOI18N
        getContentPane().add(status);
        status.setBounds(470, 100, 200, 16);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(bundle.getString("telaLogin.jLabel5.text")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(500, 140, 50, 16);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(bundle.getString("telaLogin.jLabel6.text")); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(500, 200, 41, 16);

        inputPass.setText(bundle.getString("telaLogin.inputPass.text")); // NOI18N
        getContentPane().add(inputPass);
        inputPass.setBounds(500, 220, 140, 22);

        buttonLogar.setForeground(new java.awt.Color(255, 255, 255));
        buttonLogar.setText(bundle.getString("telaLogin.buttonLogar.text")); // NOI18N
        buttonLogar.setBorderPainted(false);
        buttonLogar.setContentAreaFilled(false);
        buttonLogar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonLogar.setFocusPainted(false);
        buttonLogar.setFocusable(false);
        buttonLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonLogar);
        buttonLogar.setBounds(530, 240, 80, 32);

        direitos.setForeground(new java.awt.Color(255, 255, 255));
        direitos.setText(bundle.getString("telaLogin.direitos.text")); // NOI18N
        getContentPane().add(direitos);
        direitos.setBounds(560, 310, 180, 16);

        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText(bundle.getString("telaLogin.jButton1.text")); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(510, 270, 120, 32);

        inputUser.setText(bundle.getString("telaLogin.inputUser.text")); // NOI18N
        getContentPane().add(inputUser);
        inputUser.setBounds(500, 160, 140, 24);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_registro/fundo-preto-background90-1024x640.jpg"))); // NOI18N
        jLabel2.setText(bundle.getString("telaLogin.jLabel2.text")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(380, 0, 370, 340);

        setSize(new java.awt.Dimension(747, 331));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        telaRegistro cn = new telaRegistro();
        cn.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buttonLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogarActionPerformed
        String p_user = inputUser.getText();
        String p_pass = inputPass.getText();
        
        if(p_user.equals("") || p_pass.equals("")){
            status.setForeground(Color.red);
            status.setText("Preencha os campos vazios!");
            return;
        }
        
        for(int i=0; i<=dados.position;i++){
            if(p_user.equals(dados.user[i]) && p_pass.equals(dados.password[i])){
                status.setForeground(Color.green);
                status.setText("Acesso permitido!");
                return;
            }
        }
        status.setForeground(Color.red);
        status.setText("Senha ou usuário incorretos!");
    }//GEN-LAST:event_buttonLogarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLogar;
    private javax.swing.JLabel direitos;
    private javax.swing.JPasswordField inputPass;
    private javax.swing.JTextField inputUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel status;
    private javax.swing.JLabel tittle;
    // End of variables declaration//GEN-END:variables
}
